// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLz_JIz7I7inIziST57QSkOoBjp42Tv40',
    appId: '1:388227024926:android:d9595a3ec0882e1814860f',
    messagingSenderId: '388227024926',
    projectId: 'aplikasi-transaksi-fiva-frozen',
    databaseURL: 'https://aplikasi-transaksi-fiva-frozen-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-transaksi-fiva-frozen.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLz_JIz7I7inIziST57QSkOoBjp42Tv40',
    appId: '1:388227024926:web:d9595a3ec0882e1814860f',
    messagingSenderId: '388227024926',
    projectId: 'aplikasi-transaksi-fiva-frozen',
    authDomain: 'aplikasi-transaksi-fiva-frozen.firebaseapp.com',
    databaseURL: 'https://aplikasi-transaksi-fiva-frozen-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-transaksi-fiva-frozen.firebasestorage.app',
  );
}
